title: BDJ â€“ Publishing on Blu-ray Disc with Java.
email: service@bdj.pub
description: Publishing on Blu-ray Disc with Java â¤ï¸â€ğŸ”¥ğŸ’¿â˜• BD-J, HD Cookbook
url: "https://bdj.pub"

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - docker-compose.yml
